### ISSUE TITLE
confint_betabinom.model_estimation: Stop for methods Kaplan and Nelson

### ISSUE THREAD

**Issue by Tim-TU** [Tim-TU/weibulltools#141]
If `*$data$method %in% c("kaplan", "nelson")` method confint_betabinom.model_estimation should stop with the message that no ranks are available or something like this. 

For the old interface one could check for the `all(is.na(ranks))` and if so throw the same error.

**Comment by DavidBarke** [comment]
We don't have this information for the old interface. `confint_betabinom.default` creates a fake model_estimation. Its data element does not have a rank column.
