### ISSUE TITLE
Stabilizing print methods

### ISSUE THREAD

**Issue by Tim-TU** [Tim-TU/weibulltools#180]
I think we should implement a routine that checks for required columns. 

I would prefer to have a normal print if column `cdf_estimation_method` is not available. See attached reprex. 

What do you think? Could this also happen for other prints? 

``` r
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(weibulltools)

rel_tbl <- reliability_data(data = shock, x = distance, status = status)
cdf_tbl <- estimate_cdf(rel_tbl, "kaplan")

cdf_tbl %>% select(x, prob)
#> Warning: Unknown or uninitialised column: `cdf_estimation_method`.

#> Warning: Unknown or uninitialised column: `cdf_estimation_method`.
#> CDF estimation for methods '':
#> # A tibble: 38 x 2
#>        x    prob
#>    <int>   <dbl>
#>  1  6700  0.0263
#>  2  6950 NA     
#>  3  7820 NA     
#>  4  8790 NA     
#>  5  9120  0.0550
#>  6  9660 NA     
#>  7  9820 NA     
#>  8 11310 NA     
#>  9 11690 NA     
#> 10 11850 NA     
#> # ... with 28 more rows
```

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavidBarke** [comment]
For consistency, a `wt_cdf_estimation` should always have a column named `cdf_estimation_method`. If you omit this column, you should not expect the print method to work properly. You would have to manually remove the `wt_cdf_estimation` class to avoid getting a warning.

I suppose this can happen with any print if the object no longer conforms to its class. But that is the responsibility of the user and should not be captured.

**Comment by Tim-TU** [comment]
If I were the user, I would not know that there is a print method for this and would expect to be able to apply `dplyr` verbs to the object and not get warnings when filtering, selecting, mutating, etc.

But the warning is very clear so maybe you are right... let's have this issue in mind.

**Comment by DavidBarke** [comment]
I get your point. The heading on top of the tibble print should be an indicator that some custom printing is done.

However, filtering and mutating should work as intended as long as you don't remove the `cdf_estimation_method` column.

**Comment by DavidBarke** [comment]
If you really need to deselect `cdf_estimation_method` you'd need to remove class `wt_cdf_estimation` to get a meanigful print.
