### ISSUE TITLE
`delta_method()`: Split argument `p` in arguments `p` and `q`

### ISSUE THREAD

**Issue by Tim-TU** [Tim-TU/weibulltools#204]
While reviewing the documentation, I noticed that the use of the `delta_method()` could be a bit confusing regarding the argument `p`. 

It is said that `p` must be either probabilities or quantiles. 

Would it be better to have an argument `p` that is for the probabilities and an argument `q` that is for the quantiles. In this case, only one of the two can be specified and must be in line with the selection made in `direction`.

@DavidBarke, what's your opinion on this issue?

**Comment by DavidBarke** [comment]
In this case the argument `direction` would be rather redundant and should henceforth be removed, right?

Renaming the argument to `x` would be also possible.

If we keep it like it is, a reference to `direction` should be made in the documentation of `p`.
