### ISSUE TITLE
Rank Regression by Benard’s approximation

### ISSUE THREAD

**Issue by sangwoo-statistics** [Tim-TU/weibulltools#224]
Hi.
Thanks for helping many people , interested in using weibull analysis.

I have tried to understand how rank_regression function works, based on sample data.
But I couldn't get same rank regression outputs from manual works.
I have added R codes to explain what I am trying to say.

library(weibulltools)
x1 <- c(315,386,487,509,512,613,660,725,753,811,848,872)
x1.fit <- estimate_cdf(x2, method="mr", status=1)
x1.fit.mr <- rank_regression(x2.fit, dist="weibull")
x1.fit.mr$shape_scale_coefficients

y<- log(-log(1-x1.fit$prob)) #median ranks by benard
ln_x1 <- log(x1)
mr.reg.fit <- lm(y~ln_x1)

mr.reg.fit$coefficients[2] #beta
exp(-mr.reg.fit$coefficients[1]/mr.reg.fit$coefficients[2]) #eta

Would appreciate if you leave any comments about it.
Best regards, Sangwoo.

**Comment by Tim-TU** [comment]
Sorry for the late reply. 

Attached the explanation: 

``` r
library(weibulltools)
x1 <- c(315,386,487,509,512,613,660,725,753,811,848,872)
x2 <- reliability_data(x = x1, status = rep(1, length(x1)))

x1.fit <- estimate_cdf(x2, method = "mr")

# The default behaviour in rank_regression is direction = "x_on_y"; x ~ y
x1.fit.mr <- rank_regression(x1.fit, dist="weibull", direction = "x_on_y")
x1.fit.mr$shape_scale_coefficients
#>        eta       beta 
#> 693.382089   3.533522


y<- log(-log(1-x1.fit$prob)) #median ranks by benard
ln_x1 <- log(x1)

# This is the rank regression y ~ x
mr.reg.fit <- lm(y~ln_x1)

mr.reg.fit$coefficients[2] #beta
#>    ln_x1 
#> 3.460732
exp(-mr.reg.fit$coefficients[1]/mr.reg.fit$coefficients[2]) #eta
#> (Intercept) 
#>    695.5716

matrix(
  c(x1.fit.mr$shape_scale_coefficients, 
    exp(-mr.reg.fit$coefficients[1]/mr.reg.fit$coefficients[2]), 
    mr.reg.fit$coefficients[2]
  ),
  byrow = TRUE, 
  ncol = 2
)
#>          [,1]     [,2]
#> [1,] 693.3821 3.533522
#> [2,] 695.5716 3.460732


# The rank_regression using direction "y_on_x": 
x1.fit.mr_yonx <- rank_regression(x1.fit, dist="weibull", direction = "y_on_x")
x1.fit.mr_yonx$shape_scale_coefficients
#>        eta       beta 
#> 695.571598   3.460732

matrix(
  c(x1.fit.mr_yonx$shape_scale_coefficients, 
    exp(-mr.reg.fit$coefficients[1]/mr.reg.fit$coefficients[2]), 
    mr.reg.fit$coefficients[2]
    ),
  byrow = TRUE, 
  ncol = 2
)
#>          [,1]     [,2]
#> [1,] 695.5716 3.460732
#> [2,] 695.5716 3.460732
砀
#> Error in eval(expr, envir, enclos): Objekt '砀' nicht gefunden
```

<sup>Created on 2023-02-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Tim-TU** [comment]
default of argument `direction` in `rank_regression()` is "x_on_y".

**Comment by sangwoo-statistics** [comment]
Hi.
Thanks for your feedback.
It is now clear!
Best regards, Sangwoo.

2023년 3월 4일 (토) 오후 3:42, Tim-Gunnar Hensel ***@***.***>님이 작성:
