### ISSUE TITLE
mcs_delay_report referenziert mcs_delay_report

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#33]
Soll es stattdessen mcs_delay_register sein?

**Comment by DavidBarke** [comment]
Bei register genauso

**Comment by Tim-TU** [comment]
dist_delay_register() und dist_delay_report() werden von den mcs_...() referenziert und innerhalb dieser auch aufgerufen.

**Comment by DavidBarke** [comment]
Stimmt, ich bin wohl etwas durcheinander gekommen
