### ISSUE TITLE
plot_pop(): Implementation of logistic, normal, sev, weibull3, lognormal3 and loglogistic3

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#36]

**Comment by Tim-TU** [comment]
Auch die anderen Netze könnten in plot_pop bereitgestellt werden, allerdings müssen wir uns hier dann nochmal über die Parametereingabe besprechen. Sinnvoll wäre dann wohl, dass alle Verteilungen in Form der Location-Scale-Parametrierung einzugeben sind.
