### ISSUE TITLE
mr_method: warning instead of error if censored data problem

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#38]
mr_method should filter all failures and ignore censored observations

**Comment by DavidBarke** [comment]
This has the advantage that it is much easier to compare the different methods in estimate_cdf and plot_prob afterwards

**Comment by Tim-TU** [comment]
Dann warning text überarbeiten, sodass dieser wie eine Info klingt.

**Comment by DavidBarke** [comment]
Soll die mr_methode dann nur die nicht zensierten Daten zurückgeben? Oder mit NA auffüllen?

**Comment by DavidBarke** [comment]
Soll die mr_methode dann auch die zensierten Werte mitzurückgeben oder nicht?

**Comment by Tim-TU** [comment]
Ja, mit dem Hinweis das die zensierten Daten weder für die Auswertung noch im Stichprobenumfang berücksichtigt werden.

**Comment by DavidBarke** [comment]
Habe jetzt eine message statt einer warning genommen. Über den Wortlaut können wir nochmal reden
