### ISSUE TITLE
reliability_data: Default for id

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#55]
What would be a meaningful default? Is it in fact "XXXXXX"?

**Comment by Tim-TU** [comment]
Could be also unique numbers from 1 to vector length or to the nrow of a df. I've used 'XXXXXX' since it is obvious that this is still a placeholder. 

You could also use a string pasting together 'ID' and the corresponding row line or element number, i.e. 'ID1', 'ID2,...

**Comment by DavidBarke** [comment]
I like the idea of pasting together a string with a consecutive number. Using "" would produce only consecutive numbers as characters.

**Comment by DavidBarke** [comment]
Default is now id=NULL. In this case the ID is ID1, ID2 and so on. I let go of the idea with a character of length 1 as this would break the data based approach (ambiguity whether id is a column name or the prefix)
