### ISSUE TITLE
cdf_estimate: nelson method reaches 1

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#56]
take data from example page of `reliability_data()`
run `estimate_cdf()` with `methods = "nelson"`
the 12 last estimated failure probabilities are 1

Is that meaningful?

**Comment by Tim-TU** [comment]
https://github.com/cran/weibulltools/blob/52b39b74b0f51f321fcc842bbe5919bd3e49498f/R/probability_estimators.R#L259

`length(x)`: the length of the vector x no longer corresponds to the sample size **n = 72** but is reduced by the number of duplicated x values, thus `n_in` equals 55 and not 72 ... 

I've already replaced `length(x)` with `nrow(data)` and will close this issue with the next pull request.

**Comment by Tim-TU** [comment]
solved by #67
