### ISSUE TITLE
rank_regression: return "real" cdf_estimation

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#58]
Currently cdf_estimation is created artificially. To achieve the "real" cdf_estimation `rank_regression_` has to be introduced. This function gets called from `rank_regression.cdf_estimation` as well as from `rank_regression.default`.

**Comment by Tim-TU** [comment]
What is meant with "created artificially" and what is meant by "real" cdf_estimation? 

`estimate_cdf()` is a non-paramtric approach whereas `rank_regression` (needs non-parametric cdf estimate) estimates the parameters and therefore the linearized cdf in a parametric context
