### ISSUE TITLE
Restructure documentation of S3 generics and methods

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#77]
- [x] rank_regression
- [x] ml_estimation
- [x] mixmod_regression
- [x] r_squared_profiling
- [x] plot_mod_mix

**Comment by DavidBarke** [comment]
Maybe use S4 methods?

**Comment by Tim-TU** [comment]
Same names for dispatch arguments but separate doc sites

**Comment by Tim-TU** [comment]
Documentation of r_squared_profiling functions... Use 'R-Squared-Profile Function' instead of '\eqn{R²}-Profile' Function as the titles.
