### ISSUE TITLE
Support multiple methods

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#87]
- [x] rank_regression
- [x] mixmod_regression
- [x] plot_mod
- [x] plot_mod_mix
- [x] plot_conf
- [x] plot_prob_mix

**Comment by Tim-TU** [comment]
#48

**Comment by DavidBarke** [comment]
- [ ] rank_regression
- [ ] ml_estimation
- [ ] mixmod_regression
- [ ] mixmod_em
- [ ] plot_mod
- [ ] plot_mod_mix
